### ISSUE TITLE
Nothing happens when I click on "Start using" button

### ISSUE THREAD

**Issue by radovix** [MarkWiki/mwapp#1]
Nothing happens when I click on "Start using" button. I think this really is a big problem.

**Comment by radovix** [comment]
Why is this closed?

**Comment by AleksandarDev** [comment]
On our Roadmap there is an item "GitHub integration" which will enable you to log in using GitHub. When this feature is done, the button you mentioned will become available.

**Comment by AleksandarDev** [comment]
Fixed in version `0.1.5`
